name: CS 61A Resources
author: Tammy Nguyen
url: tmmydngyn.com
baseurl: /cs61a-resources
email: tammynguyen@berkeley.edu
disqus: tmmydngyn
permalink: none
description: Tammy's 61A resources.

markdown: kramdown
highlighter: pygments
future: false
