name: CS 61A Resources
author: Tammy Nguyen
url: tmmydngyn.com
baseurl: /cs61a
email: tammynguyen@berkeley.edu
disqus: tmmydngyn
permalink: none
description: Tammy's Spring 2018 CS 61A resources.

markdown: kramdown
highlighter: pygments
